---
  - name: Download Tomcat
    get_url: url={{ tomcat_tar_url }} dest={{ apps_path }}/tomcat.tar.gz mode=0755 

  - name: Extract Tomcat
    command: "tar zxf {{ apps_path }}/tomcat.tar.gz  -C {{ tomcat_path }} --strip-components 1"
   
  - name: Remove ROOT folder initially
    command: rm -rf {{ remove_root }}
    
  - name: Copy bikes Project War Files
    copy: src=/root/.jenkins/workspace/production/ansible/warstorage/{{ artifact }} dest={{ tomcat_path }}/webapps/ROOT.war mode=0644
    notify: 
    - Restart Tomcat
