---
# vars file for apache
tomcat_path: /opt/SP/apps/tomcat
tomcat_tar_url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.10/bin/apache-tomcat-9.0.10.tar.gz
remove_root: /opt/SP/apps/tomcat/webapps/ROOT
html_path: /var/www/html
artifact: userproject-0.0.1-SNAPSHOT.war
apps_path: /opt/SP/apps


